# Generated by Django 4.2.2 on 2023-06-20 17:20

from django.db import migrations
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', users.models.UserCManager()),
            ],
        ),
    ]
