# Generated by Django 4.2.1 on 2023-05-28 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_message_sending_attempt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sending',
            name='frequency',
            field=models.CharField(choices=[('1 раз в день', '1 раз в день'), ('1 раз в неделю', '1 раз в неделю'), ('1 раз в месяц', '1 раз в месяц')], max_length=14),
        ),
        migrations.AlterField(
            model_name='sending',
            name='status',
            field=models.CharField(choices=[('создана', 'Создана'), ('завершена', 'Завершена'), ('запущена', 'Запущена')], default='created', max_length=50),
        ),
    ]
