# Generated by Django 4.2.1 on 2023-05-31 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_attempt_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attempt',
            name='response',
            field=models.TextField(blank=True, null=True, verbose_name='Ответ сервера'),
        ),
        migrations.AlterField(
            model_name='attempt',
            name='sending',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.sending', verbose_name='Рассылка'),
        ),
        migrations.AlterField(
            model_name='attempt',
            name='status',
            field=models.CharField(choices=[('в процессе', 'В процессе'), ('успешно', 'Успешно'), ('не удачно', 'Не удачно')], max_length=50, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='message',
            field=models.TextField(verbose_name='Сообщение'),
        ),
        migrations.AlterField(
            model_name='message',
            name='body',
            field=models.TextField(verbose_name='Сообщение'),
        ),
        migrations.AlterField(
            model_name='message',
            name='subject',
            field=models.CharField(max_length=254, verbose_name='Тема'),
        ),
        migrations.AlterField(
            model_name='sending',
            name='frequency',
            field=models.CharField(choices=[('once', '1 раз в день'), ('weekly', '1 раз в неделю'), ('monthly', '1 раз в месяц')], max_length=14, verbose_name='Периодичность'),
        ),
        migrations.AlterField(
            model_name='sending',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.message', verbose_name='Сообщение'),
        ),
        migrations.AlterField(
            model_name='sending',
            name='status',
            field=models.CharField(choices=[('Создана', 'Создана'), ('Завершена', 'Завершена'), ('Запущена', 'Запущена')], default='created', max_length=50, verbose_name='Статус'),
        ),
    ]
