# Generated by Django 4.2.1 on 2023-06-02 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_sending_frequency_alter_sending_scheduled_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attempt',
            name='sent_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Время рассылки'),
        ),
        migrations.AlterField(
            model_name='attempt',
            name='status',
            field=models.CharField(choices=[('delivered', 'доставлено'), ('not_delivered', 'не доставлено')], verbose_name='Статус'),
        ),
    ]
