# Generated by Django 4.2.2 on 2023-06-22 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_attempt_sent_at_alter_attempt_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='message',
        ),
        migrations.AddField(
            model_name='customer',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='комментарий'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(blank=True, max_length=150, null=True, verbose_name='почта'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='имя'),
        ),
    ]
