# Generated by Django 4.2.2 on 2023-06-22 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_sending_created'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sending',
            options={'permissions': [('set_send_status', 'Can set sending status')], 'verbose_name': 'Рассылка', 'verbose_name_plural': 'Рассылки'},
        ),
    ]
