# Generated by Django 4.2.2 on 2023-06-23 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_customer_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sending',
            name='status',
            field=models.CharField(choices=[('Создана', 'Создана'), ('Завершена', 'Завершена'), ('Запущена', 'Запущена')], default='Создана', max_length=50, verbose_name='Статус'),
        ),
    ]
