# Generated by Django 4.2.2 on 2023-06-27 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_sending_end_date_sending_start_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sending',
            name='created_at',
        ),
    ]
